# Generated by Django 2.1.1 on 2020-01-14 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_seession_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='seession_id',
            new_name='uid',
        ),
    ]
