# Generated by Django 2.1.1 on 2020-01-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200115_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='suggested_number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='uid',
        ),
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.CharField(default=0, max_length=100, verbose_name='ИД Игры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Игра завершена'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.CharField(default=0, max_length=255, verbose_name='ИД игрока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='game_finished',
            field=models.BooleanField(default=0, verbose_name='Завершил игру'),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='try_count',
            field=models.IntegerField(default=0, verbose_name='Попытки'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(related_name='game', through='game.PlayerGameInfo', to='game.Player'),
        ),
    ]
